CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) UNIQUE, password VARCHAR(255) NOT NULL);
CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL);
CREATE TABLE menu_items (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), description TEXT, price DECIMAL(10,2), image VARCHAR(255), category_id INT, is_available TINYINT(1) DEFAULT 1, is_veg TINYINT(1) DEFAULT 1, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE gallery (id INT AUTO_INCREMENT PRIMARY KEY, image VARCHAR(255), category VARCHAR(100));
CREATE TABLE contact_info (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(50), address TEXT, email VARCHAR(120), hours VARCHAR(150));
CREATE TABLE inquiries (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), phone VARCHAR(40), message TEXT, type VARCHAR(40), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO users(username,password) VALUES('admin','$2a$10$QIqXjmn3dDn4kXfPzowLreW4.r6hPj2V4vOrmxJ6zTDF03JxKM6W6');
